import { ContractAddresses, KnownContracts } from "./types";

const MasterCopyAddresses = {
  realityETH: "0x72d453a685c27580acDFcF495830EB16B7E165f8",
  realityERC20: "0x6f628F0c3A3Ff75c39CF310901f10d79692Ed889",
  bridge: "0x457042756F2B1056487173003D27f37644C119f3",
  delay: "0xeD2323128055cE9539c6C99e5d7EBF4CA44A2485",
  factory: "0x00000000062c52e29e8029dc2413172f6d619d85",
  exit: "0x35E35dcDc7Cd112B93C7c55987C86e5D6D419C69",
  scopeGuard: "0xfDc921764b88A889F9BFa5Ba874f77607a63b832",
  circulatingSupply: "0xd7a85e7D0813F8440602E243Acb67df3CCeb5a60",
};

// TODO: Deploy Roles Modifier master copy to missing chains
export const CONTRACT_ADDRESSES: Record<number, ContractAddresses> = {
  1: {
    ...MasterCopyAddresses,
    roles: "",
  },
  4: {
    ...MasterCopyAddresses,
    roles: "0x5e3295A8c9faeFEE1Bac7A0F4797243693E862CE",
  },
  100: {
    ...MasterCopyAddresses,
    roles: "",
  },
  137: {
    ...MasterCopyAddresses,
    roles: "",
  },
  31337: {
    ...MasterCopyAddresses,
    roles: "",
  },
};

export const CONTRACT_ABIS: Record<keyof KnownContracts, string[]> = {
  realityETH: [
    `function setArbitrator(address arbitrator) public`,
    `function setQuestionTimeout(uint32 timeout) public`,
    `function setQuestionCooldown(uint32 cooldown) public`,
    `function setMinimumBond(uint256 bond) public`,
    `function setTemplate(bytes32 template) public`,
    `function setAnswerExpiration(uint32 expiration) public`,
    `function setUp(bytes memory initParams) public`,
    `function initialized() public view returns (bool)`,
  ],
  realityERC20: [
    `function setArbitrator(address arbitrator) public`,
    `function setQuestionTimeout(uint32 timeout) public`,
    `function setQuestionCooldown(uint32 cooldown) public`,
    `function setMinimumBond(uint256 bond) public`,
    `function setTemplate(bytes32 template) public`,
    `function setAnswerExpiration(uint32 expiration) public`,
    `function setUp(bytes memory initParams) public`,
    `function initialized() public view returns (bool)`,
  ],
  bridge: [
    `function setAmb(address _amb) public`,
    `function setChainId(bytes32 _chainId) public`,
    `function setOwner(address _owner) public`,
    `function setUp(bytes memory initParams) public`,
    `function initialized() public view returns (bool)`,
  ],
  delay: [
    `function setTxCooldown(uint256 cooldown) public`,
    `function setTxExpiration(uint256 expiration) public`,
    `function setUp(bytes memory initParams) public`,
    `function enableModule(address module) public`,
    `function txCooldown() public view returns (uint256)`,
    `function txExpiration() public view returns (uint256)`,
    `function getModulesPaginated(
      address start, 
      uint256 pageSize
    ) external view returns (
      address[] memory array, 
      address next
    )`,
    `function initialized() public view returns (bool)`,
  ],
  exit: [
    `function setUp(bytes memory initParams) public`,
    `function exit(uint256 amountToRedeem, address[] calldata tokens) public`,
    `function addToDenylist(address[] calldata tokens) external`,
    `function removeFromDenylist(address[] calldata tokens) external `,
    `function setDesignatedToken(address _token) public`,
    `function getCirculatingSupply() public view returns (uint256)`,
    `function initialized() public view returns (bool)`,
  ],
  scopeGuard: [
    `function setUp(bytes memory initParams) public`,
    `function checkTransaction(
      address to,
      uint256,
      bytes memory data,
      uint8 operation,
      uint256,
      uint256,
      uint256,
      address,
      address payable,
      bytes memory,
      address
    ) external view`,
    `function isAllowedToDelegateCall(address target) public view returns (bool)`,
    `function isAllowedFunction(address target, bytes4 functionSig) public view returns (bool)`,
    `function isScoped(address target) public view returns (bool)`,
    `function isAllowedTarget(address target) public view returns (bool)`,
    `function disallowFunction(address target, bytes4 functionSig) public returns (bool)`,
    `function allowFunction(address target, bytes4 functionSig) public`,
    `function toggleScoped(address target) public`,
    `function disallowDelegateCall(address target) public`,
    `function allowDelegateCall(address target) public`,
    `function disallowTarget(address target) public`,
    `function allowTarget(address target) public`,
    `function initialized() public view returns (bool)`,
  ],
  factory: [
    `function deployModule(
      address masterCopy, 
      bytes memory initializer,
      uint256 saltNonce
    ) public returns (address proxy)`,
  ],
  circulatingSupply: [
    `function setUp(bytes memory initializeParams) public`,
    `function get() public view returns (uint256 circulatingSupply)`,
    `function setToken(address _token) public`,
    `function removeExclusion(address prevExclusion, address exclusion) public`,
    `function exclude(address exclusion) public`,
    `function isExcluded(address _exclusion) public view returns (bool)`,
    `function getExclusionsPaginated(address start, uint256 pageSize) public view`,
  ],
  roles: [
    "error ArraysDifferentLength()",
    "error ModuleTransactionFailed()",
    "error NoMembership()",
    "error SetUpModulesAlreadyCalled()",
    "event AllowTarget(uint16 role, address targetAddress, bool canSend, bool canDelegate)",
    "event AllowTargetPartially(uint16 role, address targetAddress, bool canSend, bool canDelegate)",
    "event AssignRoles(address module, uint16[] roles)",
    "event AvatarSet(address indexed previousAvatar, address indexed newAvatar)",
    "event ChangedGuard(address guard)",
    "event DisabledModule(address module)",
    "event EnabledModule(address module)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event RevokeTarget(uint16 role, address targetAddress)",
    "event RolesModSetup(address indexed initiator, address indexed owner, address indexed avatar, address target)",
    "event ScopeAllowFunction(uint16 role, address targetAddress, bytes4 selector)",
    "event ScopeFunction(uint16 role, address targetAddress, bytes4 functionSig, bool[] paramIsScoped, bool[] paramIsDynamic, uint8[] paramCompType, bytes[] paramCompValue)",
    "event ScopeParameter(uint16 role, address targetAddress, bytes4 functionSig, uint8 paramIndex, bool isDynamic, uint8 compType, bytes compValue)",
    "event ScopeParameterAsOneOf(uint16 role, address targetAddress, bytes4 functionSig, uint8 paramIndex, bool isDynamic, bytes[] compValues)",
    "event ScopeRevokeFunction(uint16 role, address targetAddress, bytes4 selector)",
    "event SetDefaultRole(address module, uint16 defaultRole)",
    "event SetMulitSendAddress(address multiSendAddress)",
    "event TargetSet(address indexed previousTarget, address indexed newTarget)",
    "event UnscopeParameter(uint16 role, address targetAddress, bytes4 functionSig, uint8 paramIndex)",
    "function allowTarget(uint16 role, address targetAddress, bool canSend, bool canDelegate)",
    "function allowTargetPartially(uint16 role, address targetAddress, bool canSend, bool canDelegate)",
    "function assignRoles(address module, uint16[] _roles, bool[] memberOf)",
    "function avatar() view returns (address)",
    "function defaultRoles(address) view returns (uint16)",
    "function disableModule(address prevModule, address module)",
    "function enableModule(address module)",
    "function execTransactionFromModule(address to, uint256 value, bytes data, uint8 operation) returns (bool success)",
    "function execTransactionFromModuleReturnData(address to, uint256 value, bytes data, uint8 operation) returns (bool, bytes)",
    "function execTransactionWithRole(address to, uint256 value, bytes data, uint8 operation, uint16 role, bool shouldRevert) returns (bool success)",
    "function execTransactionWithRoleReturnData(address to, uint256 value, bytes data, uint8 operation, uint16 role, bool shouldRevert) returns (bool success, bytes returnData)",
    "function getGuard() view returns (address _guard)",
    "function getModulesPaginated(address start, uint256 pageSize) view returns (address[] array, address next)",
    "function guard() view returns (address)",
    "function isModuleEnabled(address _module) view returns (bool)",
    "function multiSend() view returns (address)",
    "function owner() view returns (address)",
    "function renounceOwnership()",
    "function revokeTarget(uint16 role, address targetAddress)",
    "function scopeAllowFunction(uint16 role, address targetAddress, bytes4 functionSig)",
    "function scopeFunction(uint16 role, address targetAddress, bytes4 functionSig, bool[] isParamScoped, bool[] isParamDynamic, uint8[] paramCompType, bytes[] paramCompValue)",
    "function scopeParameter(uint16 role, address targetAddress, bytes4 functionSig, uint8 paramIndex, bool isDynamic, uint8 compType, bytes compValue)",
    "function scopeParameterAsOneOf(uint16 role, address targetAddress, bytes4 functionSig, uint8 paramIndex, bool isDynamic, bytes[] compValues)",
    "function scopeRevokeFunction(uint16 role, address targetAddress, bytes4 functionSig)",
    "function setAvatar(address _avatar)",
    "function setDefaultRole(address module, uint16 role)",
    "function setGuard(address _guard)",
    "function setMultiSend(address _multiSend)",
    "function setTarget(address _target)",
    "function setUp(bytes initParams)",
    "function target() view returns (address)",
    "function transferOwnership(address newOwner)",
    "function unscopeParameter(uint16 role, address targetAddress, bytes4 functionSig, uint8 paramIndex)",
  ],
};
